export PROJECT=aptiva-medical
export PAT=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
export REGION=us-east1
export NAME=docai-service
export GCP_DOCAI_REGION=us
export GCP_DOCAI_PROCESSOR_ID=adf4737ca774e0a6